version: "3.9"

services:
  iachatbuilder:
    build:
      context: .
      dockerfile: Dock/Dockerfile
    container_name: iachatbuilder
    environment:
      OPENAI_MODEL: "gpt-4o-mini"
    volumes:
      - ./app/uploads:/app/uploads
    restart: unless-stopped
