version: "3.9"

services:
  iachatpro3:
    build:
      context: .
      dockerfile: Dock/Dockerfile
    container_name: iachatpro3
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Mexico_City
      - OPENAI_API_KEY=sk-svcacct-HaptIC3j7rjc5RzqUZ2S0lzHqqb1coVzeBzTduSMpPD8QrsqpodQNBUL1UoO6XzsuAM_6PCzpxT3BlbkFJQDQYhJou4u9al_Bk5ipuGpbN1W6fUlghxoFivAWR-Ksw4glVMwXevbUrPuSJqhIxQ6dzknEkUAw0WVTH1iFGyaAiz523DXEqF1RREjjmMALmsZEewPpPKAUnY7kXqLyKs4A
      - OPENAI_MODEL=gpt-4o-mini
    volumes:
      - ./app:/app
      - ./app/uploads:/app/uploads
    restart: unless-stopped
