version: "3.8"
services:
  gptfileapp:
    build: .
    container_name: gpt-file-processor
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app/uploads:/app/uploads
      - ./app/downloads:/app/downloads
      - ./app/logs:/app/logs
    restart: unless-stopped
