version: "3.8"
services:
  gptfileapp:
    build: .
    container_name: gpt-file-processor
    ports:
      - "8080:8080"
    environment:
       OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./app/uploads:/app/uploads
      - ./app/downloads:/app/downloads
      - ./app/logs:/app/logs
    restart: unless-stopped

