services:
  iachat:
    build:
      context: .
      dockerfile: Dock/Dockerfile
    container_name: iachat_pro_v3
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app/uploads:/app/uploads
    restart: unless-stopped
