version: "3.9"

services:
  iachatpro3:
    build:
      context: .
      dockerfile: Dock/Dockerfile
    container_name: iachatpro3
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Mexico_City
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
    volumes:
      - ./app/uploads:/app/uploads
    restart: unless-stopped
